#!/usr/bin/bash -e

[ ! -d /usr/local/bin ] && echo "No usr bin space." && exit 1
[ ! -d /etc/systemd/system ] && echo "Cannot install for SystemD." && exit 1

make install

cp ./cpu-control-c /usr/local/bin/
cp ./cpu-control-c.service /etc/systemd/system/

chmod 640 /etc/systemd/system/cpu-control-c.service

systemctl daemon-reload
systemctl enable cpu-control-c
systemctl start cpu-control-c
